#!/bin/bash

# Define image name
IMAGE_NAME="f1db"
VERSION="26.0.0"

echo "Building Docker image: $IMAGE_NAME:$VERSION..."

# Build the image
# --rm removes intermediate containers after a successful build
docker build -t $IMAGE_NAME:$VERSION --build-arg VERSION=$VERSION -f .devcontainer/Dockerfile --target builder .

if [ $? -eq 0 ]; then
    echo "✅ Build successful!"
else
    echo "❌ Build failed!"
    exit 1
fi